version: '3.8'

services:
  mysql_db: 
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306"

volumes:
  db-data:
